version: "3.1"

services:
    be:
        build: .
        ports:
            - "8080:80"

    db:
        image: mysql:8.0
        ports:
            - "1337:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: quiz_db
            MYSQL_USER: quiz_user
            MYSQL_PASSWORD: quiz_password
            MYSQL_ROOT_PASSWORD: quiz_password
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: quiz_user
            MYSQL_PASSWORD: quiz_password
            MYSQL_ROOT_PASSWORD: quiz_password
volumes:
    persistent:

networks:
  default:
    external: true
    name: quiz-backend_default





